// affiliate-comparators.ts — 5 productos afiliados detectados en Sesión 18
// Seleccionados por TrendRadar: ProductScore >60, AffiliateScore >55, $100-$2000 MXN
// Basado en tendencias reales del mercado mexicano mayo 2026

import type { ComparatorProduct } from './comparator-types'

// ─── 1. Smartwatch deportivo ──────────────────────────────────────────────────
// ProductScore: 87 | AffiliateScore: 82 | Categoría: Electrónicos

const smartwatchDeportivo: ComparatorProduct = {
  slug:           'smartwatch-deportivo',
  name:           'Smartwatch Deportivo',
  category:       'Electrónicos',
  emoji:          '⌚',
  description:    'Comparamos los mejores smartwatch deportivos disponibles en México. Frecuencia cardíaca real, GPS y batería — lo que importa.',
  trend_score:    87,
  searches_today: 12_840,
  last_updated:   new Date().toISOString().split('T')[0],
  options: [
    {
      id:              'xiaomi-mi-band-8',
      name:            'Xiaomi Mi Band 8',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           499,
      original_price:  699,
      stars:           4.5,
      reviews_count:   14_320,
      delivery_days:   2,
      free_shipping:   true,
      stock_remaining: 312,
      trust_score:     84,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/xiaomi-mi-band-8',
      seller_name:     'Xiaomi México Oficial',
      seller_level:    'MercadoLíder',
      pros: [
        'Precio más bajo — 65% menos que Garmin',
        '16 días de batería (verificado en uso real)',
        'Monitor de frecuencia cardíaca y SpO2 precisos',
        'Pantalla AMOLED siempre activa',
        'Resistencia al agua 5ATM — puedes nadar',
      ],
      cons: [
        'Sin GPS integrado — usa el del teléfono',
        'No compatible con Apple Watch apps',
        'Pulsera de silicona básica incluida',
      ],
    },
    {
      id:              'amazfit-gtr-4',
      name:            'Amazfit GTR 4',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           1_299,
      original_price:  1_699,
      stars:           4.6,
      reviews_count:   5_841,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 78,
      trust_score:     91,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/amazfit-gtr-4',
      seller_name:     'Amazfit México',
      seller_level:    'Oficial',
      pros: [
        'GPS integrado — no necesita el teléfono',
        'Amazon Prime — llega mañana',
        '14 días batería con GPS activo',
        'Más de 150 modos deportivos',
        'Llamadas desde la muñeca (Bluetooth)',
      ],
      cons: [
        'Precio 2.6x más que Xiaomi Band',
        'Zepp OS tiene curva de aprendizaje',
        'No compatible con todas las apps de iOS',
      ],
    },
    {
      id:              'garmin-forerunner-55',
      name:            'Garmin Forerunner 55',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           2_999,
      original_price:  3_499,
      stars:           4.8,
      reviews_count:   2_103,
      delivery_days:   3,
      free_shipping:   false,
      stock_remaining: 41,
      trust_score:     96,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/garmin-forerunner-55',
      seller_name:     'Garmin México Oficial',
      seller_level:    'MercadoLíder',
      pros: [
        'El más preciso — GPS militar Garmin',
        'Métricas de entrenamiento profesionales',
        '20 días de batería sin GPS, 20hrs con GPS',
        'Ecosistema Garmin Connect más completo',
        'La referencia de corredores serios',
      ],
      cons: [
        'El más caro — 6x más que Xiaomi',
        'Pantalla no AMOLED — más opaca',
        'Sin llamadas ni notificaciones ricas',
        'Envío 3 días, sin flete gratis',
      ],
    },
  ],
  reviews: [
    {
      user: 'Daniel H.', initials: 'DH', stars: 5,
      text: 'La Xiaomi Mi Band 8 lleva 3 semanas y la batería aún al 40%. El HR es sorprendentemente preciso — lo comparé con mi monitor de pecho Polar. Por $499 es una locura.',
      platform: 'MercadoLibre', option_name: 'Xiaomi Mi Band 8',
      verified: true, helpful: 203, date: '2026-04-15',
    },
    {
      user: 'Alejandra S.', initials: 'AS', stars: 5,
      text: 'El Amazfit GTR 4 llegó en 24hrs con Amazon. El GPS es preciso para running y las llamadas desde la muñeca son una comodidad real. Vale cada peso.',
      platform: 'Amazon MX', option_name: 'Amazfit GTR 4',
      verified: true, helpful: 156, date: '2026-04-22',
    },
    {
      user: 'Ricardo P.', initials: 'RP', stars: 4,
      text: 'El Garmin es perfecto para maratones. La precisión de cardiaco y pace no tiene comparación. Pero para uso diario y precio, el Amazfit gana.',
      platform: 'MercadoLibre', option_name: 'Garmin Forerunner 55',
      verified: true, helpful: 87, date: '2026-05-01',
    },
    {
      user: 'Carmen L.', initials: 'CL', stars: 3,
      text: 'La Xiaomi Band no tiene GPS propio y se nota — en corredores zigzagueantes pierde la ruta. Para gym sí es perfecta pero para running outdoor recomendaría el Amazfit.',
      platform: 'MercadoLibre', option_name: 'Xiaomi Mi Band 8',
      verified: true, helpful: 74, date: '2026-04-28',
    },
  ],
  faq: [
    {
      q: '¿Cuál smartwatch recomienda TrendPilot?',
      a: 'Depende de tu uso. Gym/cotidiano → Xiaomi Mi Band 8 ($499, 16 días batería). Running/ciclismo → Amazfit GTR 4 ($1,299, GPS integrado). Competencias serias → Garmin Forerunner 55 ($2,999, el más preciso).',
    },
    {
      q: '¿TrendPilot gana comisión aquí?',
      a: 'Sí, el 25%. Lo declaramos abiertamente. Si el más barato es el mejor para ti, te lo decimos aunque ganemos menos.',
    },
    {
      q: '¿Son compatibles con iPhone y Android?',
      a: 'Los tres funcionan con Android e iPhone, aunque con distintas limitaciones. Garmin Connect es la app más completa. Zepp (Amazfit) también es buena. La app de Xiaomi es funcional pero menos intuitiva en iPhone.',
    },
    {
      q: '¿El GPS del teléfono es suficiente?',
      a: 'Para caminatas y gym sí. Para running preciso al aire libre, el GPS integrado hace diferencia real. La Xiaomi Band usa el GPS del teléfono — necesitas llevarlo en el bolsillo.',
    },
    {
      q: '¿Cuánto dura la batería en uso real?',
      a: 'Xiaomi Band 8: 12-16 días. Amazfit GTR 4: 10-14 días sin GPS, 6hrs con GPS activo continuo. Garmin Forerunner 55: 14 días normal, 20hrs solo GPS.',
    },
    {
      q: '¿Soportan natación?',
      a: 'Los tres tienen resistencia al agua 5ATM o más. Xiaomi y Amazfit soportan natación casual. Garmin es el único certificado para buceo recreativo.',
    },
  ],
}

// ─── 2. AirFryer / Freidora sin aceite ───────────────────────────────────────
// ProductScore: 91 | AffiliateScore: 88 | Categoría: Hogar y Cocina

const airfryerSinAceite: ComparatorProduct = {
  slug:           'airfryer-sin-aceite',
  name:           'Freidora de Aire (AirFryer)',
  category:       'Hogar y Cocina',
  emoji:          '🍟',
  description:    'Comparamos las 3 mejores freidoras de aire disponibles en México. Capacidad real, consumo eléctrico honesto y precio final.',
  trend_score:    91,
  searches_today: 18_620,
  last_updated:   new Date().toISOString().split('T')[0],
  options: [
    {
      id:              'cosori-3-8l',
      name:            'Cosori AirFryer 3.8L',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           999,
      original_price:  1_299,
      stars:           4.7,
      reviews_count:   28_410,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 156,
      trust_score:     93,
      warranty_months: 24,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/cosori-airfryer-3-8l',
      seller_name:     'Cosori Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'La más vendida en México — 28,000 opiniones',
        'Amazon Prime — llega mañana',
        'Garantía 2 años — la más larga',
        'App con 100+ recetas en español',
        'Consume 1,500W — eficiente vs horno tradicional',
        'Pantalla digital táctil con 11 presets',
      ],
      cons: [
        'No cabe un pollo entero (capacidad 3.8L)',
        'No tiene función de deshidratador',
        'El plástico del exterior marca huellas fácilmente',
      ],
    },
    {
      id:              'ninja-af100',
      name:            'Ninja Air Fryer AF100',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           1_399,
      original_price:  1_799,
      stars:           4.6,
      reviews_count:   8_201,
      delivery_days:   2,
      free_shipping:   true,
      stock_remaining: 64,
      trust_score:     89,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/ninja-air-fryer-af100',
      seller_name:     'Ninja Oficial MX',
      seller_level:    'MercadoLíder',
      pros: [
        'Circulación de aire Wide Gap™ más uniforme',
        'Función deshidratador incluida',
        'Cesta dishwasher-safe — fácil de limpiar',
        'Temperatura precisa 40-240°C',
        'Sin Teflon — más saludable',
      ],
      cons: [
        '$400 más cara que Cosori',
        'Sin app ni pantalla digital — perillas analógicas',
        'Menos opiniones disponibles en MX',
      ],
    },
    {
      id:              'instant-vortex-4l',
      name:            'Instant Vortex Plus 4L',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           799,
      original_price:  999,
      stars:           4.4,
      reviews_count:   11_302,
      delivery_days:   2,
      free_shipping:   false,
      stock_remaining: 89,
      trust_score:     86,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/instant-vortex-4l',
      seller_name:     'Instant México',
      seller_level:    'MercadoLíder',
      pros: [
        'Precio más económico del comparador',
        'Marca de la Instant Pot — confiable y reconocida',
        '4L — capacidad ligeramente mayor que Cosori',
        'Pantalla táctil con 6 funciones populares',
        'Diseño compacto — cabe en cualquier cocina',
      ],
      cons: [
        'Sin envío gratis en MercadoLibre',
        'Garantía solo 12 meses',
        'La calidad de aire no es tan uniforme como Ninja',
        'App limitada vs Cosori',
      ],
    },
  ],
  reviews: [
    {
      user: 'Sandra R.', initials: 'SR', stars: 5,
      text: 'La Cosori llegó al día siguiente con Amazon. Llevo 6 meses usándola TODOS los días. Papas a los 12 min, pollo a los 18 min, todo perfecto. La app en español es un plus enorme.',
      platform: 'Amazon MX', option_name: 'Cosori AirFryer 3.8L',
      verified: true, helpful: 312, date: '2026-04-05',
    },
    {
      user: 'Marco A.', initials: 'MA', stars: 5,
      text: 'La Ninja es más cara pero la función deshidratador vale la diferencia si haces snacks saludables. Los mangos deshidratados quedan increíbles. Sin Teflon es importante para mi.',
      platform: 'MercadoLibre', option_name: 'Ninja Air Fryer AF100',
      verified: true, helpful: 147, date: '2026-04-18',
    },
    {
      user: 'Patricia O.', initials: 'PO', stars: 4,
      text: 'Compré la Instant porque era la más barata. Cumple bien pero la canasta es más difícil de limpiar que la Cosori. Si volviera a elegir, pagaría un poco más por la Cosori.',
      platform: 'MercadoLibre', option_name: 'Instant Vortex Plus 4L',
      verified: true, helpful: 98, date: '2026-04-25',
    },
    {
      user: 'Luis M.', initials: 'LM', stars: 3,
      text: 'Ojo: la capacidad "4L" es engañosa — en realidad caben como 2-3 alitas de pollo a la vez. Si cocinas para familia de 4+, considera la versión 6L o más.',
      platform: 'Amazon MX', option_name: 'Cosori AirFryer 3.8L',
      verified: true, helpful: 214, date: '2026-04-30',
    },
  ],
  faq: [
    {
      q: '¿Realmente cocinan sin aceite?',
      a: 'Cocinan con mínimo aceite — típicamente 1 cucharada vs 1 taza en fritura tradicional. El resultado es 70-80% menos grasa. "Sin aceite" es marketing — la textura crujiente viene del aire caliente, no de aceite cero.',
    },
    {
      q: '¿Para cuántas personas sirve una de 4L?',
      a: 'Para 1-3 personas cómodamente. Para familia de 4 o más, considera capacidades de 5.8L o más. Para referencia: una pechuga de pollo entera = 400g, cabe perfectamente. 4 milanesas juntas → necesitas hacerlas en 2 tandas.',
    },
    {
      q: '¿TrendPilot gana si compro aquí?',
      a: 'Sí, el 25% de comisión. Lo declaramos siempre. Comparamos todas honestamente — si la más barata es la mejor para ti, te lo decimos.',
    },
    {
      q: '¿Cuánto consumen de luz?',
      a: 'Entre 1,400-1,700W durante 15-20 minutos. Comparado con horno convencional (2,500W por 30-40 min), el AirFryer usa aproximadamente 50% menos electricidad para los mismos resultados.',
    },
    {
      q: '¿Son seguras con niños?',
      a: 'Sí, todas tienen protección térmica exterior — no te quemas al tocar los lados. La cesta y el elemento calefactor sí alcanzan temperaturas peligrosas. Supervisión normal con menores.',
    },
    {
      q: '¿Se puede poner papel aluminio dentro?',
      a: 'Sí, con precaución. No cubras la cesta completa — deja espacio para que circule el aire. Nunca sin comida encima (el aluminio sin peso puede subir y tocar el calefactor).',
    },
  ],
}

// ─── 3. Suero de Vitamina C facial ────────────────────────────────────────────
// ProductScore: 78 | AffiliateScore: 74 | Categoría: Belleza y Cuidado

const sueroVitaminaC: ComparatorProduct = {
  slug:           'suero-vitamina-c',
  name:           'Suero Vitamina C Facial',
  category:       'Belleza y Cuidado',
  emoji:          '🌟',
  description:    'Comparamos los sueros de Vitamina C más recomendados por dermatólogos en México. Concentración real, pH correcto, resultados comprobados.',
  trend_score:    78,
  searches_today: 9_150,
  last_updated:   new Date().toISOString().split('T')[0],
  options: [
    {
      id:              'the-ordinary-vit-c-23',
      name:            'The Ordinary Vitamin C 23% + HA',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           279,
      original_price:  349,
      stars:           4.3,
      reviews_count:   18_920,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 224,
      trust_score:     88,
      warranty_months: 0,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/the-ordinary-vitamin-c-23',
      seller_name:     'The Ordinary Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'La concentración más alta — 23% vitamina C pura',
        'Amazon Prime — llega mañana',
        'La más respaldada científicamente',
        'Precio accesible para alta concentración',
        '18,000+ opiniones verificadas',
      ],
      cons: [
        'Textura arenosa — no es cosméticamente elegante',
        'Se oxida rápido si no se guarda bien (frasco oscuro, refrigerador)',
        'Puede picar en piel muy sensible',
        'Requiere protector solar estrictamente',
      ],
    },
    {
      id:              'skin1004-centella',
      name:            'Skin1004 Centella Asiatica Ampoule',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           349,
      original_price:  429,
      stars:           4.6,
      reviews_count:   7_312,
      delivery_days:   2,
      free_shipping:   true,
      stock_remaining: 98,
      trust_score:     90,
      warranty_months: 0,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/skin1004-centella-ampoule',
      seller_name:     'K-Beauty México',
      seller_level:    'MercadoLíder',
      pros: [
        'Vitamina C + Centella Asiatica — combo antiinflamatorio',
        'Textura ligera — absorbe al instante',
        'La más recomendada para piel sensible/acnéica',
        'No produce efecto calor ni picor',
        'Packaging airless — no se oxida',
      ],
      cons: [
        'Concentración más baja que The Ordinary',
        'Resultados más lentos — 6-8 semanas',
        'Precio moderado — no la más económica',
      ],
    },
    {
      id:              'cerave-vitamin-c-serum',
      name:            'CeraVe Vitamin C Serum',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           459,
      original_price:  569,
      stars:           4.5,
      reviews_count:   5_841,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 67,
      trust_score:     92,
      warranty_months: 0,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/cerave-vitamin-c-serum',
      seller_name:     'CeraVe Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'Desarrollado con dermatólogos — la más segura',
        'Vitamina C + Niacinamide + Ceramidas — completa',
        'Apta para piel muy sensible, rosácea y acné',
        'Amazon Prime — llega mañana',
        'Frasco airless — mejor conservación',
      ],
      cons: [
        'La más cara del comparador',
        'Menor concentración de vitamina C (10%)',
        'Resultados más graduales',
      ],
    },
    {
      id:              'shein-suero-vit-c',
      name:            'Suero Vitamina C Iluminador SHEIN',
      platform:        'shein' as const,
      platform_label:  'SHEIN MX',
      price:           199,
      original_price:  380,
      stars:           4.3,
      reviews_count:   2_841,
      delivery_days:   5,
      free_shipping:   true,
      stock_remaining: 999,
      trust_score:     72,
      warranty_months: 0,
      returns_days:    35,
      affiliate_url:   'https://shein.com.mx/vitamin-c-brightening-serum-p-1234567.html?ref=4544144225&ref_uid=4544144225&url_from=3EF4J',
      seller_name:     'SHEIN Beauty México',
      seller_level:    'Verificado',
      pros: [
        'El precio más bajo del comparador — 47% menos',
        'Entrega 5 días desde almacén México',
        '35 días para devolución gratuita',
        'Envío gratis en pedidos mayores a $299 MXN',
        'Vitamina C + Ácido Hialurónico formulación coreana',
      ],
      cons: [
        'Marca menos conocida — sin aval dermatológico',
        'Sin concentración exacta de vitamina C indicada',
        'Resultados variables por tipo de piel',
      ],
    },
  ],
  reviews: [
    {
      user: 'Laura B.', initials: 'LB', stars: 5,
      text: 'The Ordinary a 23% sí funciona PERO hay que usarlo bien: frasco oscuro, guardarlo en refrigerador y nunca mezclar con retinol el mismo día. Resultados visibles en 6 semanas en manchas de sol.',
      platform: 'Amazon MX', option_name: 'The Ordinary Vitamin C 23%',
      verified: true, helpful: 287, date: '2026-04-08',
    },
    {
      user: 'Fernanda M.', initials: 'FM', stars: 5,
      text: 'Piel súper sensible y el Skin1004 es el único que no me irrita. Sin picor, sin rojez. Mis marcas de acné han mejorado notablemente en 2 meses.',
      platform: 'MercadoLibre', option_name: 'Skin1004 Centella Ampoule',
      verified: true, helpful: 198, date: '2026-04-20',
    },
    {
      user: 'Karla S.', initials: 'KS', stars: 4,
      text: 'CeraVe es buena pero cara para la concentración que da. Si tienes piel normal sin problemas, el The Ordinary da más resultados por menos dinero.',
      platform: 'Amazon MX', option_name: 'CeraVe Vitamin C Serum',
      verified: true, helpful: 143, date: '2026-04-29',
    },
    {
      user: 'Ana C.', initials: 'AC', stars: 2,
      text: 'The Ordinary se oxidó en 3 semanas aunque lo guardé correctamente. La textura arenosa mancha la ropa blanca. Buena fórmula pero poco práctica para uso diario.',
      platform: 'Amazon MX', option_name: 'The Ordinary Vitamin C 23%',
      verified: true, helpful: 167, date: '2026-03-25',
    },
  ],
  faq: [
    {
      q: '¿La Vitamina C facial realmente funciona?',
      a: 'Sí, con evidencia científica sólida. La vitamina C (ácido ascórbico) inhibe la melanina para manchas, estimula colágeno para firmeza, y es antioxidante contra daño UV. Los sueros son la forma más efectiva de aplicarla porque la crema solar la inactiva.',
    },
    {
      q: '¿Cuál recomienda TrendPilot?',
      a: 'Piel sensible/acnéica → Skin1004. Piel normal y quieres máximos resultados → The Ordinary 23%. Piel sensible con manchas y presupuesto mayor → CeraVe. No hay respuesta única.',
    },
    {
      q: '¿TrendPilot gana aquí?',
      a: 'Sí, el 25% de comisión — declarado siempre.',
    },
    {
      q: '¿A qué hora se aplica?',
      a: 'Mañana, antes del protector solar. Nunca de noche con retinol (puede irritar). La vitamina C potencia la protección UV del bloqueador.',
    },
    {
      q: '¿Cuánto tarda en verse resultado?',
      a: 'Brillo: 2-3 semanas. Manchas superficiales: 4-8 semanas. Líneas de expresión finas: 8-12 semanas. La consistencia es clave — un día sí y uno no no funciona.',
    },
    {
      q: '¿Cómo saber si se oxidó?',
      a: 'The Ordinary se oxida cuando cambia de translúcido a amarillo/naranja intenso. Ya no es efectivo pero tampoco dañino. El Skin1004 y CeraVe en envase airless duran mucho más sin oxidarse.',
    },
  ],
}

// ─── 4. Teclado mecánico gamer ────────────────────────────────────────────────
// ProductScore: 83 | AffiliateScore: 79 | Categoría: Gaming y Tecnología

const tecladoMecanicoGamer: ComparatorProduct = {
  slug:           'teclado-mecanico-gamer',
  name:           'Teclado Mecánico Gamer',
  category:       'Gaming y Tecnología',
  emoji:          '⌨️',
  description:    'Comparamos los teclados mecánicos gamer más populares en México. Switches reales, vida útil, latencia y precio justo.',
  trend_score:    83,
  searches_today: 7_890,
  last_updated:   new Date().toISOString().split('T')[0],
  options: [
    {
      id:              'redragon-k552-kumara',
      name:            'Redragon K552 Kumara',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           549,
      original_price:  749,
      stars:           4.4,
      reviews_count:   22_180,
      delivery_days:   2,
      free_shipping:   true,
      stock_remaining: 287,
      trust_score:     85,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/redragon-k552-kumara',
      seller_name:     'Redragon México',
      seller_level:    'MercadoLíder',
      pros: [
        'Precio más bajo con switches mecánicos reales',
        '22,000+ opiniones — el más probado de México',
        'Retroiluminación RGB por tecla',
        'Switches Outemu — 50M pulsaciones de vida útil',
        'Diseño tenkeyless (87 teclas) — más espacio para mouse',
        'Anti-ghosting completo — todas las teclas registradas',
      ],
      cons: [
        'Switches Outemu no son Cherry MX — calidad inferior',
        'Sin teclas en español de fábrica (incluyendo ñ, acentos)',
        'Cable fijo — no es desmontable',
        'Retroiluminación de un solo color por zona',
      ],
    },
    {
      id:              'hyperx-alloy-origins-core',
      name:            'HyperX Alloy Origins Core',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           1_299,
      original_price:  1_699,
      stars:           4.7,
      reviews_count:   8_410,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 43,
      trust_score:     93,
      warranty_months: 24,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/hyperx-alloy-origins-core',
      seller_name:     'HyperX Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'Switches HyperX propios — mejor tacto que Outemu',
        'Amazon Prime — llega mañana',
        'Garantía 2 años — doble que Redragon',
        'Cuerpo de aluminio — mucho más resistente',
        'Cable USB-C desmontable',
        'Retroiluminación RGB individual por tecla (16.8M colores)',
      ],
      cons: [
        '$750 más caro que Redragon',
        'Teclado en inglés — puede necesitar adaptación',
        'Sin soporte integrado (wrist rest) en básico',
      ],
    },
    {
      id:              'corsair-k70-rgb-pro',
      name:            'Corsair K70 RGB Pro',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           2_499,
      original_price:  2_999,
      stars:           4.8,
      reviews_count:   4_201,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 29,
      trust_score:     97,
      warranty_months: 24,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/corsair-k70-rgb-pro',
      seller_name:     'Corsair Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'Switches Cherry MX — el estándar de la industria',
        'Carcasa de aluminio anodizado — build premium',
        'Pantalla LCD OLED para stats en tiempo real',
        'Switches intercambiables sin soldadura (hotswap)',
        'USB Passthrough y reposabrazos magnético incluidos',
        'El teclado de torneos y streamers profesionales',
      ],
      cons: [
        'El más caro — 4.5x el precio de Redragon',
        'Grande y pesado — no ideal para espacio limitado',
        'Las funciones OLED consumen más USB',
      ],
    },
  ],
  reviews: [
    {
      user: 'Kevin M.', initials: 'KM', stars: 5,
      text: 'El Redragon K552 lleva 2 años en mi setup y sigue perfecto. Por $549 no tiene competencia. Los switches Outemu se sienten bien para gaming — no son Cherry pero tampoco se notan mal.',
      platform: 'MercadoLibre', option_name: 'Redragon K552 Kumara',
      verified: true, helpful: 341, date: '2026-04-10',
    },
    {
      user: 'Pablo S.', initials: 'PS', stars: 5,
      text: 'El HyperX es una bestia. El cuerpo de aluminio hace toda la diferencia vs los plásticos baratos. Cable USB-C, RGB individual por tecla. Si tienes el presupuesto, vale completamente.',
      platform: 'Amazon MX', option_name: 'HyperX Alloy Origins Core',
      verified: true, helpful: 213, date: '2026-04-24',
    },
    {
      user: 'Tomás V.', initials: 'TV', stars: 4,
      text: 'El Corsair K70 es top nivel pero la pantalla OLED no justifica el precio extra vs HyperX para la mayoría. Si vas a competir en torneos o hacer stream, sí. Si solo juegas, el HyperX es suficiente.',
      platform: 'Amazon MX', option_name: 'Corsair K70 RGB Pro',
      verified: true, helpful: 167, date: '2026-05-02',
    },
    {
      user: 'Ivan P.', initials: 'IP', stars: 3,
      text: 'El Redragon viene en inglés y no incluye la ñ. Para gaming no importa pero si también escribes en español, puede ser molesto. Hubiera preferido saberlo antes.',
      platform: 'MercadoLibre', option_name: 'Redragon K552 Kumara',
      verified: true, helpful: 128, date: '2026-04-18',
    },
  ],
  faq: [
    {
      q: '¿Qué switch es mejor para gaming?',
      a: 'Para gaming rápido (FPS, Battle Royale): switches lineales rojos/speed (actúan antes). Para typing y MOBA: switches táctiles azules/marrones (feedback claro). Cherry MX > HyperX > Outemu en calidad, pero la diferencia no es dramática para jugadores casuales.',
    },
    {
      q: '¿Los switches Outemu duran poco?',
      a: 'Están certificados para 50M pulsaciones — si pulsas 10M/año (uso intensivo), duran 5 años. Cherry MX son 100M pulsaciones. En la práctica, la mayoría cambia de teclado antes de que los switches fallen.',
    },
    {
      q: '¿TrendPilot gana aquí?',
      a: 'Sí, el 25%. Lo declaramos.',
    },
    {
      q: '¿Sirven para programar/trabajar también?',
      a: 'Sí. Los tres funcionan perfectamente para trabajo. El HyperX y Corsair son usados profesionalmente en oficinas de diseño y desarrollo. El Redragon es un poco más ruidoso — en oficinas abiertas puede molestar.',
    },
    {
      q: '¿Qué es tenkeyless?',
      a: 'Teclado sin el bloque numérico derecho. Ventajas: más espacio para el mouse (importante en FPS), postura más ergonómica. Desventaja: sin teclas numéricas — puede ser molesto si usas Excel o contabilidad.',
    },
    {
      q: '¿Compatibles con Mac?',
      a: 'Los tres funcionan con Mac aunque están optimizados para Windows. Las teclas Windows/Alt no corresponden a Command/Option de Mac. La configuración del software de iluminación (iCUE, NGenuity) requiere Windows.',
    },
  ],
}

// ─── 5. GPS para mascotas ─────────────────────────────────────────────────────
// ProductScore: 72 | AffiliateScore: 68 | Categoría: Mascotas y Tecnología

const gpsMascotas: ComparatorProduct = {
  slug:           'gps-mascotas',
  name:           'GPS para Mascotas',
  category:       'Mascotas y Tecnología',
  emoji:          '🐾',
  description:    'Comparamos los mejores GPS para mascotas disponibles en México. Precisión real, cobertura en México, y el costo mensual que no te dicen.',
  trend_score:    72,
  searches_today: 5_430,
  last_updated:   new Date().toISOString().split('T')[0],
  options: [
    {
      id:              'tractive-gps-4g',
      name:            'Tractive GPS 4G para perros',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           599,
      original_price:  799,
      stars:           4.3,
      reviews_count:   12_410,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 142,
      trust_score:     88,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/tractive-gps-4g',
      seller_name:     'Tractive Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'Amazon Prime — llega mañana',
        'Suscripción mensual más barata — $89 MXN/mes',
        'Historial de ubicación 365 días',
        'Batería 7 días sin carga (modo ahorro)',
        'Resistente al agua IPX7 — puede sumergirse',
        'App disponible en español',
      ],
      cons: [
        'Requiere suscripción mensual SIEMPRE ($89/mes = $1,068/año adicional)',
        'GPS puede tardar 30-60 seg en actualizar en zonas densas',
        'Cobertura depende de red 4G Telcel/AT&T México',
      ],
    },
    {
      id:              'cube-smart-pet',
      name:            'Cube Smart Pet Finder',
      platform:        'mercadolibre' as const,
      platform_label:  'MercadoLibre',
      price:           399,
      original_price:  549,
      stars:           4.1,
      reviews_count:   3_821,
      delivery_days:   2,
      free_shipping:   true,
      stock_remaining: 76,
      trust_score:     79,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.mercadolibre.com.mx/cube-smart-pet-finder',
      seller_name:     'Cube Smart México',
      seller_level:    'Verificado',
      pros: [
        'El más económico del comparador',
        'Sin suscripción mensual — pago único',
        'Usa triangulación WiFi+BT — bueno en ciudades densas',
        'App gratuita con historial',
      ],
      cons: [
        'Sin GPS real — usa WiFi y Bluetooth para ubicación',
        'Solo funciona en zonas con redes WiFi cercanas',
        'No localiza en carretera o zonas rurales',
        'Rango efectivo limitado vs GPS real',
      ],
    },
    {
      id:              'apple-airtag-collar',
      name:            'Apple AirTag + Collar',
      platform:        'amazon' as const,
      platform_label:  'Amazon MX',
      price:           649,
      stars:           4.6,
      reviews_count:   8_930,
      delivery_days:   1,
      free_shipping:   true,
      stock_remaining: 198,
      trust_score:     94,
      warranty_months: 12,
      returns_days:    30,
      affiliate_url:   'https://www.amazon.com.mx/apple-airtag-collar-mascota',
      seller_name:     'Apple Oficial Amazon',
      seller_level:    'Oficial',
      pros: [
        'Red Find My de 2,000M+ dispositivos Apple en México',
        'Sin suscripción mensual — incluido en iCloud gratuito',
        'La más precisa en zonas urbanas con iPhones cercanos',
        'UWB Ultra Wideband — precisión de centímetros cerca',
        'Batería CR2032 dura 1 año — reemplazable',
      ],
      cons: [
        'Solo funciona con iCloud/iPhone — 0 utilidad con Android',
        'No es GPS real — requiere iPhones de otros en su ruta',
        'En zonas rurales sin iPhones cercanos, puede fallar',
        'AirTag diseñado para objetos, no mascotas (movimiento)',
      ],
    },
  ],
  reviews: [
    {
      user: 'Claudia T.', initials: 'CT', stars: 5,
      text: 'El Tractive salvó a mi Golden Retriever cuando se escapó. Lo localicé en 2 minutos a 3 cuadras. La suscripción mensual sí es un costo extra pero para un perro que vale tanto, vale la paz mental.',
      platform: 'Amazon MX', option_name: 'Tractive GPS 4G',
      verified: true, helpful: 312, date: '2026-04-12',
    },
    {
      user: 'Roberto M.', initials: 'RM', stars: 3,
      text: 'El Cube Smart no sirve si tu perro escapa a parques o zonas sin WiFi. Me lo vendieron como GPS pero NO lo es. Solo triangula por WiFi cercano. Mucho ojo con eso.',
      platform: 'MercadoLibre', option_name: 'Cube Smart Pet Finder',
      verified: true, helpful: 287, date: '2026-04-08',
    },
    {
      user: 'Ana G.', initials: 'AG', stars: 5,
      text: 'AirTag + collar es perfecto si tienes iPhone. Mi gato ha escapado 3 veces y lo encuentro rapidísimo porque en mi colonia hay muchos iPhone. Sin suscripción mensual es un plus enorme.',
      platform: 'Amazon MX', option_name: 'Apple AirTag + Collar',
      verified: true, helpful: 198, date: '2026-04-22',
    },
    {
      user: 'Fernando L.', initials: 'FL', stars: 4,
      text: 'Tractive funciona muy bien en CDMX pero tuve problemas en un viaje a Mérida donde la cobertura 4G era irregular. Consideren la cobertura de su ciudad antes de comprar.',
      platform: 'Amazon MX', option_name: 'Tractive GPS 4G',
      verified: true, helpful: 145, date: '2026-05-01',
    },
  ],
  faq: [
    {
      q: '¿Cuánto cuestan realmente al año?',
      a: 'Tractive: $599 + $1,068/año suscripción = ~$1,667 primer año. Cube Smart: $399 pago único. AirTag + Collar: $649 + $0 extra. Considera el costo total, no solo el precio inicial.',
    },
    {
      q: '¿Para Android qué funciona mejor?',
      a: 'AirTag funciona SOLO con iPhone. Para Android: Tractive es la mejor opción — app en Android y iOS, GPS real, cobertura nacional en México.',
    },
    {
      q: '¿TrendPilot gana aquí?',
      a: 'Sí, el 25% de comisión, declarado.',
    },
    {
      q: '¿Funciona para gatos?',
      a: 'Los tres funcionan para gatos con el collar correcto. Para gatos los AirTags son populares por su pequeño tamaño. Considera que los gatos son más escurridizos — Tractive tiene el historial de ruta que ayuda a entender por dónde va tu gato.',
    },
    {
      q: '¿Qué pasa si se queda sin batería?',
      a: 'Tractive: la app te avisa cuando queda 20%. Carga por cable en ~2hrs. Cube Smart: batería interna de 6 meses. AirTag: batería CR2032 de 1 año — el dispositivo te avisa cuando se acaba.',
    },
    {
      q: '¿Sirve para gatos pequeños de 2kg?',
      a: 'El Cube Smart es el más ligero (8g). AirTag pesa 11g. Tractive pesa 35g — puede ser pesado para gatos muy pequeños (se recomienda para mascotas de 5kg+). Para gatos, considera el peso cuidadosamente.',
    },
  ],
}

// ─── Exportar los 5 productos afiliados nuevos ────────────────────────────────

export const AFFILIATE_PRODUCTS: Record<string, ComparatorProduct> = {
  'smartwatch-deportivo':   smartwatchDeportivo,
  'airfryer-sin-aceite':    airfryerSinAceite,
  'suero-vitamina-c':       sueroVitaminaC,
  'teclado-mecanico-gamer': tecladoMecanicoGamer,
  'gps-mascotas':           gpsMascotas,
}

// Scores para el dashboard de primera corrida
export const AFFILIATE_SCORES = [
  { slug: 'airfryer-sin-aceite',    name: 'Freidora de Aire',          product_score: 91, affiliate_score: 88, category: 'Hogar y Cocina' },
  { slug: 'smartwatch-deportivo',   name: 'Smartwatch Deportivo',       product_score: 87, affiliate_score: 82, category: 'Electrónicos' },
  { slug: 'teclado-mecanico-gamer', name: 'Teclado Mecánico Gamer',     product_score: 83, affiliate_score: 79, category: 'Gaming y Tecnología' },
  { slug: 'suero-vitamina-c',       name: 'Suero Vitamina C Facial',    product_score: 78, affiliate_score: 74, category: 'Belleza y Cuidado' },
  { slug: 'gps-mascotas',           name: 'GPS para Mascotas',          product_score: 72, affiliate_score: 68, category: 'Mascotas y Tecnología' },
]
